GET http://localhost:3000/

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "partnet1@user.com",
  "password": "secret"
}

###
POST http://localhost:3000/partners
Content-Type: application/json

{
  "name": "Partner 1",
  "email": "partnet1@user.com",
  "password": "secret",
  "company_name": "Company Name 1"
}

###
POST http://localhost:3000/customers
Content-Type: application/json

{
  "email": "partnet1@user.com",
  "password": "secret",
  "address": "Address test",
  "phone": "33333333"
}

###
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Event Test 1",
  "description": "Event Description",
  "date": "2025-01-01T00:00:00",
  "location": "Street X Neighborhood Y"
}

###
GET http://localhost:3000/partners/events/10000

###
GET http://localhost:3000/events

###
GET http://localhost:3000/events/1
